#!/usr/bin/env python3
"""Writes rayman_nx/source/ro_gltrace_slots.inc: N wrapper functions gwN(a0..a9)
that forward to ro_gltrace.c's gw_call(N, ...), and the table of them."""
import sys

N = 256
ARGS = ", ".join("uintptr_t a%d" % i for i in range(10))
CALL = ", ".join("a%d" % i for i in range(10))
out = ["/* ro_gltrace_slots.inc -- generated by work/gen_gwslots.py: %d GL call wrappers. MIT. */" % N, ""]
for n in range(N):
    out.append("static uintptr_t gw%d(%s) { return gw_call(%d, %s); }" % (n, ARGS, n, CALL))
out.append("")
out.append("static const uintptr_t k_gw[RO_GW_SLOTS] = {")
for n in range(N):
    out.append("    (uintptr_t)gw%d," % n)
out.append("};")
open(sys.argv[1], "w", newline="\n").write("\n".join(out) + "\n")
print("wrote", sys.argv[1], N, "slots")
