/* imports.c -- GENERATED by runtime/tools/gen_imports.py; do not edit.
 *
 * Every import of libfmodex/libRO1Mobile that no loaded module
 * exports (gl* aside: the GL layer serves those), mapped to the host
 * function or object that serves it: b_* shims for the bionic ABI
 * (bionic_*.c, android_ndk.c, gl_*.c, the port's files), and newlib
 * directly where the two ABIs agree. Declared through asm labels so no
 * C prototype is needed (or can conflict): only the address is taken
 * here. The search over the table is the runtime's imports_lookup.c.
 *
 * Weak imports bound to NULL on purpose: none.
 * MIT.
 */
#include "imports.h"

extern const char sym___errno[] __asm__("__errno");
extern const char sym_acos[] __asm__("acos");
extern const char sym_acosf[] __asm__("acosf");
extern const char sym_asin[] __asm__("asin");
extern const char sym_atan[] __asm__("atan");
extern const char sym_atan2[] __asm__("atan2");
extern const char sym_atan2f[] __asm__("atan2f");
extern const char sym_atoi[] __asm__("atoi");
extern const char sym_b_AAssetManager_fromJava[] __asm__("b_AAssetManager_fromJava");
extern const char sym_b_AAssetManager_open[] __asm__("b_AAssetManager_open");
extern const char sym_b_AAsset_close[] __asm__("b_AAsset_close");
extern const char sym_b_AAsset_getLength[] __asm__("b_AAsset_getLength");
extern const char sym_b_AAsset_read[] __asm__("b_AAsset_read");
extern const char sym_b___aeabi_atexit[] __asm__("b___aeabi_atexit");
extern const char sym_b___android_log_print[] __asm__("b___android_log_print");
extern const char sym_b___android_log_write[] __asm__("b___android_log_write");
extern const char sym_b___assert2[] __asm__("b___assert2");
extern const char sym_b___cxa_atexit[] __asm__("b___cxa_atexit");
extern const char sym_b___cxa_finalize[] __asm__("b___cxa_finalize");
extern const char sym_b___gnu_Unwind_Find_exidx[] __asm__("b___gnu_Unwind_Find_exidx");
extern const char sym_b___sF[] __asm__("b___sF");
extern const char sym_b___stack_chk_fail[] __asm__("b___stack_chk_fail");
extern const char sym_b___stack_chk_guard[] __asm__("b___stack_chk_guard");
extern const char sym_b__ctype_[] __asm__("b__ctype_");
extern const char sym_b__tolower_tab_[] __asm__("b__tolower_tab_");
extern const char sym_b__toupper_tab_[] __asm__("b__toupper_tab_");
extern const char sym_b_abort[] __asm__("b_abort");
extern const char sym_b_accept[] __asm__("b_accept");
extern const char sym_b_access[] __asm__("b_access");
extern const char sym_b_adler32[] __asm__("b_adler32");
extern const char sym_b_bind[] __asm__("b_bind");
extern const char sym_b_btowc[] __asm__("b_btowc");
extern const char sym_b_ceil[] __asm__("b_ceil");
extern const char sym_b_chmod[] __asm__("b_chmod");
extern const char sym_b_chown[] __asm__("b_chown");
extern const char sym_b_close[] __asm__("b_close");
extern const char sym_b_connect[] __asm__("b_connect");
extern const char sym_b_crc32[] __asm__("b_crc32");
extern const char sym_b_deflate[] __asm__("b_deflate");
extern const char sym_b_deflateEnd[] __asm__("b_deflateEnd");
extern const char sym_b_deflateInit2_[] __asm__("b_deflateInit2_");
extern const char sym_b_deflateReset[] __asm__("b_deflateReset");
extern const char sym_b_dlclose[] __asm__("b_dlclose");
extern const char sym_b_dlopen[] __asm__("b_dlopen");
extern const char sym_b_dlsym[] __asm__("b_dlsym");
extern const char sym_b_exit[] __asm__("b_exit");
extern const char sym_b_fclose[] __asm__("b_fclose");
extern const char sym_b_fcntl[] __asm__("b_fcntl");
extern const char sym_b_fdopen[] __asm__("b_fdopen");
extern const char sym_b_fflush[] __asm__("b_fflush");
extern const char sym_b_floor[] __asm__("b_floor");
extern const char sym_b_floorf[] __asm__("b_floorf");
extern const char sym_b_fopen[] __asm__("b_fopen");
extern const char sym_b_fprintf[] __asm__("b_fprintf");
extern const char sym_b_fputc[] __asm__("b_fputc");
extern const char sym_b_fputs[] __asm__("b_fputs");
extern const char sym_b_fread[] __asm__("b_fread");
extern const char sym_b_fseek[] __asm__("b_fseek");
extern const char sym_b_fseeko[] __asm__("b_fseeko");
extern const char sym_b_fstat[] __asm__("b_fstat");
extern const char sym_b_ftell[] __asm__("b_ftell");
extern const char sym_b_ftello[] __asm__("b_ftello");
extern const char sym_b_fwrite[] __asm__("b_fwrite");
extern const char sym_b_getc[] __asm__("b_getc");
extern const char sym_b_gethostbyname[] __asm__("b_gethostbyname");
extern const char sym_b_gettimeofday[] __asm__("b_gettimeofday");
extern const char sym_b_getwc[] __asm__("b_getwc");
extern const char sym_b_gmtime[] __asm__("b_gmtime");
extern const char sym_b_inet_addr[] __asm__("b_inet_addr");
extern const char sym_b_inflate[] __asm__("b_inflate");
extern const char sym_b_inflateEnd[] __asm__("b_inflateEnd");
extern const char sym_b_inflateInit_[] __asm__("b_inflateInit_");
extern const char sym_b_inflateReset[] __asm__("b_inflateReset");
extern const char sym_b_ioctl[] __asm__("b_ioctl");
extern const char sym_b_listen[] __asm__("b_listen");
extern const char sym_b_longjmp[] __asm__("b_longjmp");
extern const char sym_b_lseek[] __asm__("b_lseek");
extern const char sym_b_mbrtowc[] __asm__("b_mbrtowc");
extern const char sym_b_memcpy[] __asm__("b_memcpy");
extern const char sym_b_memmove[] __asm__("b_memmove");
extern const char sym_b_memset[] __asm__("b_memset");
extern const char sym_b_modf[] __asm__("b_modf");
extern const char sym_b_open[] __asm__("b_open");
extern const char sym_b_poll[] __asm__("b_poll");
extern const char sym_b_printf[] __asm__("b_printf");
extern const char sym_b_pthread_attr_destroy[] __asm__("b_pthread_attr_destroy");
extern const char sym_b_pthread_attr_init[] __asm__("b_pthread_attr_init");
extern const char sym_b_pthread_attr_setdetachstate[] __asm__("b_pthread_attr_setdetachstate");
extern const char sym_b_pthread_attr_setstacksize[] __asm__("b_pthread_attr_setstacksize");
extern const char sym_b_pthread_cond_broadcast[] __asm__("b_pthread_cond_broadcast");
extern const char sym_b_pthread_cond_destroy[] __asm__("b_pthread_cond_destroy");
extern const char sym_b_pthread_cond_signal[] __asm__("b_pthread_cond_signal");
extern const char sym_b_pthread_cond_wait[] __asm__("b_pthread_cond_wait");
extern const char sym_b_pthread_create[] __asm__("b_pthread_create");
extern const char sym_b_pthread_getspecific[] __asm__("b_pthread_getspecific");
extern const char sym_b_pthread_key_create[] __asm__("b_pthread_key_create");
extern const char sym_b_pthread_key_delete[] __asm__("b_pthread_key_delete");
extern const char sym_b_pthread_mutex_destroy[] __asm__("b_pthread_mutex_destroy");
extern const char sym_b_pthread_mutex_init[] __asm__("b_pthread_mutex_init");
extern const char sym_b_pthread_mutex_lock[] __asm__("b_pthread_mutex_lock");
extern const char sym_b_pthread_mutex_unlock[] __asm__("b_pthread_mutex_unlock");
extern const char sym_b_pthread_mutexattr_init[] __asm__("b_pthread_mutexattr_init");
extern const char sym_b_pthread_mutexattr_settype[] __asm__("b_pthread_mutexattr_settype");
extern const char sym_b_pthread_once[] __asm__("b_pthread_once");
extern const char sym_b_pthread_self[] __asm__("b_pthread_self");
extern const char sym_b_pthread_setspecific[] __asm__("b_pthread_setspecific");
extern const char sym_b_putc[] __asm__("b_putc");
extern const char sym_b_putchar[] __asm__("b_putchar");
extern const char sym_b_puts[] __asm__("b_puts");
extern const char sym_b_putwc[] __asm__("b_putwc");
extern const char sym_b_raise[] __asm__("b_raise");
extern const char sym_b_read[] __asm__("b_read");
extern const char sym_b_recv[] __asm__("b_recv");
extern const char sym_b_remove[] __asm__("b_remove");
extern const char sym_b_rename[] __asm__("b_rename");
extern const char sym_b_rint[] __asm__("b_rint");
extern const char sym_b_select[] __asm__("b_select");
extern const char sym_b_sem_destroy[] __asm__("b_sem_destroy");
extern const char sym_b_sem_init[] __asm__("b_sem_init");
extern const char sym_b_sem_post[] __asm__("b_sem_post");
extern const char sym_b_sem_wait[] __asm__("b_sem_wait");
extern const char sym_b_send[] __asm__("b_send");
extern const char sym_b_setjmp[] __asm__("b_setjmp");
extern const char sym_b_setlocale[] __asm__("b_setlocale");
extern const char sym_b_setsockopt[] __asm__("b_setsockopt");
extern const char sym_b_setvbuf[] __asm__("b_setvbuf");
extern const char sym_b_snprintf[] __asm__("b_snprintf");
extern const char sym_b_socket[] __asm__("b_socket");
extern const char sym_b_sprintf[] __asm__("b_sprintf");
extern const char sym_b_sqrt[] __asm__("b_sqrt");
extern const char sym_b_sqrtf[] __asm__("b_sqrtf");
extern const char sym_b_stat[] __asm__("b_stat");
extern const char sym_b_strerror[] __asm__("b_strerror");
extern const char sym_b_strftime[] __asm__("b_strftime");
extern const char sym_b_syscall[] __asm__("b_syscall");
extern const char sym_b_time[] __asm__("b_time");
extern const char sym_b_ungetc[] __asm__("b_ungetc");
extern const char sym_b_ungetwc[] __asm__("b_ungetwc");
extern const char sym_b_unlink[] __asm__("b_unlink");
extern const char sym_b_usleep[] __asm__("b_usleep");
extern const char sym_b_utime[] __asm__("b_utime");
extern const char sym_b_vsnprintf[] __asm__("b_vsnprintf");
extern const char sym_b_vsprintf[] __asm__("b_vsprintf");
extern const char sym_b_wcrtomb[] __asm__("b_wcrtomb");
extern const char sym_b_wcscpy[] __asm__("b_wcscpy");
extern const char sym_b_wcsftime[] __asm__("b_wcsftime");
extern const char sym_b_wcsncpy[] __asm__("b_wcsncpy");
extern const char sym_b_wcstombs[] __asm__("b_wcstombs");
extern const char sym_b_wctob[] __asm__("b_wctob");
extern const char sym_b_write[] __asm__("b_write");
extern const char sym_b_writev[] __asm__("b_writev");
extern const char sym_calloc[] __asm__("calloc");
extern const char sym_cos[] __asm__("cos");
extern const char sym_cosf[] __asm__("cosf");
extern const char sym_exp[] __asm__("exp");
extern const char sym_fmodf[] __asm__("fmodf");
extern const char sym_free[] __asm__("free");
extern const char sym_frexp[] __asm__("frexp");
extern const char sym_iswctype[] __asm__("iswctype");
extern const char sym_ldexp[] __asm__("ldexp");
extern const char sym_log[] __asm__("log");
extern const char sym_log10[] __asm__("log10");
extern const char sym_log10f[] __asm__("log10f");
extern const char sym_lrand48[] __asm__("lrand48");
extern const char sym_lrintf[] __asm__("lrintf");
extern const char sym_malloc[] __asm__("malloc");
extern const char sym_memchr[] __asm__("memchr");
extern const char sym_memcmp[] __asm__("memcmp");
extern const char sym_memmem[] __asm__("memmem");
extern const char sym_pow[] __asm__("pow");
extern const char sym_powf[] __asm__("powf");
extern const char sym_qsort[] __asm__("qsort");
extern const char sym_realloc[] __asm__("realloc");
extern const char sym_sin[] __asm__("sin");
extern const char sym_sinf[] __asm__("sinf");
extern const char sym_srand48[] __asm__("srand48");
extern const char sym_sscanf[] __asm__("sscanf");
extern const char sym_strcat[] __asm__("strcat");
extern const char sym_strchr[] __asm__("strchr");
extern const char sym_strcmp[] __asm__("strcmp");
extern const char sym_strcoll[] __asm__("strcoll");
extern const char sym_strcpy[] __asm__("strcpy");
extern const char sym_strdup[] __asm__("strdup");
extern const char sym_strlen[] __asm__("strlen");
extern const char sym_strncasecmp[] __asm__("strncasecmp");
extern const char sym_strncat[] __asm__("strncat");
extern const char sym_strncmp[] __asm__("strncmp");
extern const char sym_strncpy[] __asm__("strncpy");
extern const char sym_strrchr[] __asm__("strrchr");
extern const char sym_strstr[] __asm__("strstr");
extern const char sym_strtod[] __asm__("strtod");
extern const char sym_strtol[] __asm__("strtol");
extern const char sym_strxfrm[] __asm__("strxfrm");
extern const char sym_swprintf[] __asm__("swprintf");
extern const char sym_tan[] __asm__("tan");
extern const char sym_tanf[] __asm__("tanf");
extern const char sym_towlower[] __asm__("towlower");
extern const char sym_towupper[] __asm__("towupper");
extern const char sym_wcscoll[] __asm__("wcscoll");
extern const char sym_wcslen[] __asm__("wcslen");
extern const char sym_wcsxfrm[] __asm__("wcsxfrm");
extern const char sym_wctype[] __asm__("wctype");
extern const char sym_wmemchr[] __asm__("wmemchr");
extern const char sym_wmemcmp[] __asm__("wmemcmp");
extern const char sym_wmemcpy[] __asm__("wmemcpy");
extern const char sym_wmemmove[] __asm__("wmemmove");
extern const char sym_wmemset[] __asm__("wmemset");

DynLibFunction dcr_imports[] = {
    {"AAssetManager_fromJava", (uintptr_t)sym_b_AAssetManager_fromJava},
    {"AAssetManager_open", (uintptr_t)sym_b_AAssetManager_open},
    {"AAsset_close", (uintptr_t)sym_b_AAsset_close},
    {"AAsset_getLength", (uintptr_t)sym_b_AAsset_getLength},
    {"AAsset_read", (uintptr_t)sym_b_AAsset_read},
    {"__aeabi_atexit", (uintptr_t)sym_b___aeabi_atexit},
    {"__android_log_print", (uintptr_t)sym_b___android_log_print},
    {"__android_log_write", (uintptr_t)sym_b___android_log_write},
    {"__assert2", (uintptr_t)sym_b___assert2},
    {"__cxa_atexit", (uintptr_t)sym_b___cxa_atexit},
    {"__cxa_finalize", (uintptr_t)sym_b___cxa_finalize},
    {"__errno", (uintptr_t)sym___errno},
    {"__gnu_Unwind_Find_exidx", (uintptr_t)sym_b___gnu_Unwind_Find_exidx},
    {"__sF", (uintptr_t)sym_b___sF},
    {"__stack_chk_fail", (uintptr_t)sym_b___stack_chk_fail},
    {"__stack_chk_guard", (uintptr_t)sym_b___stack_chk_guard},
    {"_ctype_", (uintptr_t)sym_b__ctype_},
    {"_tolower_tab_", (uintptr_t)sym_b__tolower_tab_},
    {"_toupper_tab_", (uintptr_t)sym_b__toupper_tab_},
    {"abort", (uintptr_t)sym_b_abort},
    {"accept", (uintptr_t)sym_b_accept},
    {"access", (uintptr_t)sym_b_access},
    {"acos", (uintptr_t)sym_acos},
    {"acosf", (uintptr_t)sym_acosf},
    {"adler32", (uintptr_t)sym_b_adler32},
    {"asin", (uintptr_t)sym_asin},
    {"atan", (uintptr_t)sym_atan},
    {"atan2", (uintptr_t)sym_atan2},
    {"atan2f", (uintptr_t)sym_atan2f},
    {"atoi", (uintptr_t)sym_atoi},
    {"bind", (uintptr_t)sym_b_bind},
    {"btowc", (uintptr_t)sym_b_btowc},
    {"calloc", (uintptr_t)sym_calloc},
    {"ceil", (uintptr_t)sym_b_ceil},
    {"chmod", (uintptr_t)sym_b_chmod},
    {"chown", (uintptr_t)sym_b_chown},
    {"close", (uintptr_t)sym_b_close},
    {"connect", (uintptr_t)sym_b_connect},
    {"cos", (uintptr_t)sym_cos},
    {"cosf", (uintptr_t)sym_cosf},
    {"crc32", (uintptr_t)sym_b_crc32},
    {"deflate", (uintptr_t)sym_b_deflate},
    {"deflateEnd", (uintptr_t)sym_b_deflateEnd},
    {"deflateInit2_", (uintptr_t)sym_b_deflateInit2_},
    {"deflateReset", (uintptr_t)sym_b_deflateReset},
    {"dlclose", (uintptr_t)sym_b_dlclose},
    {"dlopen", (uintptr_t)sym_b_dlopen},
    {"dlsym", (uintptr_t)sym_b_dlsym},
    {"exit", (uintptr_t)sym_b_exit},
    {"exp", (uintptr_t)sym_exp},
    {"fclose", (uintptr_t)sym_b_fclose},
    {"fcntl", (uintptr_t)sym_b_fcntl},
    {"fdopen", (uintptr_t)sym_b_fdopen},
    {"fflush", (uintptr_t)sym_b_fflush},
    {"floor", (uintptr_t)sym_b_floor},
    {"floorf", (uintptr_t)sym_b_floorf},
    {"fmodf", (uintptr_t)sym_fmodf},
    {"fopen", (uintptr_t)sym_b_fopen},
    {"fprintf", (uintptr_t)sym_b_fprintf},
    {"fputc", (uintptr_t)sym_b_fputc},
    {"fputs", (uintptr_t)sym_b_fputs},
    {"fread", (uintptr_t)sym_b_fread},
    {"free", (uintptr_t)sym_free},
    {"frexp", (uintptr_t)sym_frexp},
    {"fseek", (uintptr_t)sym_b_fseek},
    {"fseeko", (uintptr_t)sym_b_fseeko},
    {"fstat", (uintptr_t)sym_b_fstat},
    {"ftell", (uintptr_t)sym_b_ftell},
    {"ftello", (uintptr_t)sym_b_ftello},
    {"fwrite", (uintptr_t)sym_b_fwrite},
    {"getc", (uintptr_t)sym_b_getc},
    {"gethostbyname", (uintptr_t)sym_b_gethostbyname},
    {"gettimeofday", (uintptr_t)sym_b_gettimeofday},
    {"getwc", (uintptr_t)sym_b_getwc},
    {"gmtime", (uintptr_t)sym_b_gmtime},
    {"inet_addr", (uintptr_t)sym_b_inet_addr},
    {"inflate", (uintptr_t)sym_b_inflate},
    {"inflateEnd", (uintptr_t)sym_b_inflateEnd},
    {"inflateInit_", (uintptr_t)sym_b_inflateInit_},
    {"inflateReset", (uintptr_t)sym_b_inflateReset},
    {"ioctl", (uintptr_t)sym_b_ioctl},
    {"iswctype", (uintptr_t)sym_iswctype},
    {"ldexp", (uintptr_t)sym_ldexp},
    {"listen", (uintptr_t)sym_b_listen},
    {"log", (uintptr_t)sym_log},
    {"log10", (uintptr_t)sym_log10},
    {"log10f", (uintptr_t)sym_log10f},
    {"longjmp", (uintptr_t)sym_b_longjmp},
    {"lrand48", (uintptr_t)sym_lrand48},
    {"lrintf", (uintptr_t)sym_lrintf},
    {"lseek", (uintptr_t)sym_b_lseek},
    {"malloc", (uintptr_t)sym_malloc},
    {"mbrtowc", (uintptr_t)sym_b_mbrtowc},
    {"memchr", (uintptr_t)sym_memchr},
    {"memcmp", (uintptr_t)sym_memcmp},
    {"memcpy", (uintptr_t)sym_b_memcpy},
    {"memmem", (uintptr_t)sym_memmem},
    {"memmove", (uintptr_t)sym_b_memmove},
    {"memset", (uintptr_t)sym_b_memset},
    {"modf", (uintptr_t)sym_b_modf},
    {"open", (uintptr_t)sym_b_open},
    {"poll", (uintptr_t)sym_b_poll},
    {"pow", (uintptr_t)sym_pow},
    {"powf", (uintptr_t)sym_powf},
    {"printf", (uintptr_t)sym_b_printf},
    {"pthread_attr_destroy", (uintptr_t)sym_b_pthread_attr_destroy},
    {"pthread_attr_init", (uintptr_t)sym_b_pthread_attr_init},
    {"pthread_attr_setdetachstate", (uintptr_t)sym_b_pthread_attr_setdetachstate},
    {"pthread_attr_setstacksize", (uintptr_t)sym_b_pthread_attr_setstacksize},
    {"pthread_cond_broadcast", (uintptr_t)sym_b_pthread_cond_broadcast},
    {"pthread_cond_destroy", (uintptr_t)sym_b_pthread_cond_destroy},
    {"pthread_cond_signal", (uintptr_t)sym_b_pthread_cond_signal},
    {"pthread_cond_wait", (uintptr_t)sym_b_pthread_cond_wait},
    {"pthread_create", (uintptr_t)sym_b_pthread_create},
    {"pthread_getspecific", (uintptr_t)sym_b_pthread_getspecific},
    {"pthread_key_create", (uintptr_t)sym_b_pthread_key_create},
    {"pthread_key_delete", (uintptr_t)sym_b_pthread_key_delete},
    {"pthread_mutex_destroy", (uintptr_t)sym_b_pthread_mutex_destroy},
    {"pthread_mutex_init", (uintptr_t)sym_b_pthread_mutex_init},
    {"pthread_mutex_lock", (uintptr_t)sym_b_pthread_mutex_lock},
    {"pthread_mutex_unlock", (uintptr_t)sym_b_pthread_mutex_unlock},
    {"pthread_mutexattr_init", (uintptr_t)sym_b_pthread_mutexattr_init},
    {"pthread_mutexattr_settype", (uintptr_t)sym_b_pthread_mutexattr_settype},
    {"pthread_once", (uintptr_t)sym_b_pthread_once},
    {"pthread_self", (uintptr_t)sym_b_pthread_self},
    {"pthread_setspecific", (uintptr_t)sym_b_pthread_setspecific},
    {"putc", (uintptr_t)sym_b_putc},
    {"putchar", (uintptr_t)sym_b_putchar},
    {"puts", (uintptr_t)sym_b_puts},
    {"putwc", (uintptr_t)sym_b_putwc},
    {"qsort", (uintptr_t)sym_qsort},
    {"raise", (uintptr_t)sym_b_raise},
    {"read", (uintptr_t)sym_b_read},
    {"realloc", (uintptr_t)sym_realloc},
    {"recv", (uintptr_t)sym_b_recv},
    {"remove", (uintptr_t)sym_b_remove},
    {"rename", (uintptr_t)sym_b_rename},
    {"rint", (uintptr_t)sym_b_rint},
    {"select", (uintptr_t)sym_b_select},
    {"sem_destroy", (uintptr_t)sym_b_sem_destroy},
    {"sem_init", (uintptr_t)sym_b_sem_init},
    {"sem_post", (uintptr_t)sym_b_sem_post},
    {"sem_wait", (uintptr_t)sym_b_sem_wait},
    {"send", (uintptr_t)sym_b_send},
    {"setjmp", (uintptr_t)sym_b_setjmp},
    {"setlocale", (uintptr_t)sym_b_setlocale},
    {"setsockopt", (uintptr_t)sym_b_setsockopt},
    {"setvbuf", (uintptr_t)sym_b_setvbuf},
    {"sin", (uintptr_t)sym_sin},
    {"sinf", (uintptr_t)sym_sinf},
    {"snprintf", (uintptr_t)sym_b_snprintf},
    {"socket", (uintptr_t)sym_b_socket},
    {"sprintf", (uintptr_t)sym_b_sprintf},
    {"sqrt", (uintptr_t)sym_b_sqrt},
    {"sqrtf", (uintptr_t)sym_b_sqrtf},
    {"srand48", (uintptr_t)sym_srand48},
    {"sscanf", (uintptr_t)sym_sscanf},
    {"stat", (uintptr_t)sym_b_stat},
    {"strcat", (uintptr_t)sym_strcat},
    {"strchr", (uintptr_t)sym_strchr},
    {"strcmp", (uintptr_t)sym_strcmp},
    {"strcoll", (uintptr_t)sym_strcoll},
    {"strcpy", (uintptr_t)sym_strcpy},
    {"strdup", (uintptr_t)sym_strdup},
    {"strerror", (uintptr_t)sym_b_strerror},
    {"strftime", (uintptr_t)sym_b_strftime},
    {"strlen", (uintptr_t)sym_strlen},
    {"strncasecmp", (uintptr_t)sym_strncasecmp},
    {"strncat", (uintptr_t)sym_strncat},
    {"strncmp", (uintptr_t)sym_strncmp},
    {"strncpy", (uintptr_t)sym_strncpy},
    {"strrchr", (uintptr_t)sym_strrchr},
    {"strstr", (uintptr_t)sym_strstr},
    {"strtod", (uintptr_t)sym_strtod},
    {"strtol", (uintptr_t)sym_strtol},
    {"strxfrm", (uintptr_t)sym_strxfrm},
    {"swprintf", (uintptr_t)sym_swprintf},
    {"syscall", (uintptr_t)sym_b_syscall},
    {"tan", (uintptr_t)sym_tan},
    {"tanf", (uintptr_t)sym_tanf},
    {"time", (uintptr_t)sym_b_time},
    {"towlower", (uintptr_t)sym_towlower},
    {"towupper", (uintptr_t)sym_towupper},
    {"ungetc", (uintptr_t)sym_b_ungetc},
    {"ungetwc", (uintptr_t)sym_b_ungetwc},
    {"unlink", (uintptr_t)sym_b_unlink},
    {"usleep", (uintptr_t)sym_b_usleep},
    {"utime", (uintptr_t)sym_b_utime},
    {"vsnprintf", (uintptr_t)sym_b_vsnprintf},
    {"vsprintf", (uintptr_t)sym_b_vsprintf},
    {"wcrtomb", (uintptr_t)sym_b_wcrtomb},
    {"wcscoll", (uintptr_t)sym_wcscoll},
    {"wcscpy", (uintptr_t)sym_b_wcscpy},
    {"wcsftime", (uintptr_t)sym_b_wcsftime},
    {"wcslen", (uintptr_t)sym_wcslen},
    {"wcsncpy", (uintptr_t)sym_b_wcsncpy},
    {"wcstombs", (uintptr_t)sym_b_wcstombs},
    {"wcsxfrm", (uintptr_t)sym_wcsxfrm},
    {"wctob", (uintptr_t)sym_b_wctob},
    {"wctype", (uintptr_t)sym_wctype},
    {"wmemchr", (uintptr_t)sym_wmemchr},
    {"wmemcmp", (uintptr_t)sym_wmemcmp},
    {"wmemcpy", (uintptr_t)sym_wmemcpy},
    {"wmemmove", (uintptr_t)sym_wmemmove},
    {"wmemset", (uintptr_t)sym_wmemset},
    {"write", (uintptr_t)sym_b_write},
    {"writev", (uintptr_t)sym_b_writev},
    {"", 0},
};

int dcr_imports_count = (int)(sizeof(dcr_imports) / sizeof(dcr_imports[0])) - 1;
